//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okulotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ILCELER
    {
        public int id { get; set; }
        public int il_id { get; set; }
        public string ilce_adi { get; set; }
    }
}
